language: node_js
node_js:
- '8'
branches:
  only:
  - master
before_script:
- npm install -g --silent @angular/cli
script:
- ng build --prod
- chmod +x dist
- chmod +x dist/banking
before_deploy:
- ls
- ls dist
- ls dist/banking
- sudo cp manifest.yml dist/banking
- sudo cp Staticfile dist/banking
- ls dist/banking
- cd dist/banking
deploy:
  provider: cloudfoundry
  username: jgsistem@gmail.com
  password: 
    secure: AclbuDyI1A6O2qiHdcui+cmyfJ1RnB4zx310Xxczgja3vEoDjJPlAGnEngm3eSCyVN5itO0Oat2469BiAQKS1AfaNffiU7tDi/olj+qyd9LWB3156mJfrUKVlrHUIeYZEt4L66LGtVhvfNeb5zRJtz1qmHm/afHkBA9aNuGFoS39CFga5mYPuyNh1n4c+zyK8PfKk/zl0iydvok+iHxk76NR8MVcQ90+2xZUqtV7ggWJ4lvT0sCIIX5edW+Z8Mq0jGiIO2G0mMLCC50jquexykgmcBMZO5Nq1q9VHvvchqUqKCAVEJMDPZHqwWhnVoVU+sSer8f3uSFpjoCI1VgSSrq9WNswmqg89tFx/cDbdixg8S6LXOQglseVs5GBmvi2DyoaXqzjoGgpK0QPfhFZkp4mOs8OdFV7KorBUhQ+UD9GAEHMXSQ1mhg/upGStRb6/yKPZp59U0OCLu1nt2oSjB4T2P8b6iVI4lGQKzdLAzeGEKxkbr85oPGlo/qkdvXwMb1iI2uwxhWebfsQ0CtEBhbzY+nDIqhbx5vUwXAivSb9SPJwoS7Kg/Gq75YywS7XMGrBlToamJKUQJJTttZkn4LUckqRFh4ZCVOfEYPP4yIllH77alxySV2dsj4Mv2TxINVEJLMAwtPQ443Rq/MvpL9bCsSZvNTKB6m5ApRc/5A=
  api: https://api.run.pivotal.io
  organization: research-org
  space: development
  skip_cleanup: true
notifications:
  email:
    on_failure: change
    on_success: change
